/**
 * EL PATIO ANTIGUO - Main Scripts
 */

document.addEventListener('DOMContentLoaded', () => {

    // 1. Navbar Scroll Effect
    const navbar = document.getElementById('navbar');
    const pageType = navbar ? navbar.getAttribute('data-page-type') : 'inner';

    window.addEventListener('scroll', () => {
        if (!navbar) return;
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            if (pageType === 'home') {
                navbar.classList.remove('scrolled');
            }
        }
    });

    // 2. Carousel Controller Class
    class Carousel {
        constructor(id, interval = 5000) {
            this.carousel = document.getElementById(id);
            if (!this.carousel) return;

            this.slides = this.carousel.querySelectorAll('.carousel-item');
            this.nextBtn = this.carousel.querySelector('.next');
            this.prevBtn = this.carousel.querySelector('.prev');
            this.currentSlide = 0;
            this.interval = interval;
            this.autoSlide = null;

            this.init();
        }

        init() {
            if (this.slides.length <= 1) return;

            if (this.nextBtn) this.nextBtn.addEventListener('click', () => this.next());
            if (this.prevBtn) this.prevBtn.addEventListener('click', () => this.prev());

            this.startAuto();
        }

        showSlide(index) {
            this.slides.forEach(slide => slide.classList.remove('active'));
            this.currentSlide = (index + this.slides.length) % this.slides.length;
            this.slides[this.currentSlide].classList.add('active');
        }

        next() {
            this.showSlide(this.currentSlide + 1);
            this.resetAuto();
        }

        prev() {
            this.showSlide(this.currentSlide - 1);
            this.resetAuto();
        }

        startAuto() {
            this.autoSlide = setInterval(() => this.showSlide(this.currentSlide + 1), this.interval);
        }

        resetAuto() {
            clearInterval(this.autoSlide);
            this.startAuto();
        }
    }

    // Initialize Carousels
    new Carousel('hero-carousel', 6000);
    new Carousel('gallery-carousel', 4000);

    // 3. Scroll Reveal Animation
    const revealElements = document.querySelectorAll('.reveal');
    const revealOnScroll = () => {
        revealElements.forEach(el => {
            const elementTop = el.getBoundingClientRect().top;
            if (elementTop < window.innerHeight - 150) el.classList.add('active');
        });
    };
    window.addEventListener('scroll', revealOnScroll);
    revealOnScroll();

    // 4. Smooth Scroll
    document.querySelectorAll('a[href^="#"]').forEach(anchor => {
        anchor.addEventListener('click', function (e) {
            const href = this.getAttribute('href');
            if (href === '#' || href.startsWith('http') || href.includes('/')) return;

            const target = document.querySelector(href);
            if (target) {
                e.preventDefault();
                target.scrollIntoView({ behavior: 'smooth' });
            }
        });
    });

    // 5. Language Switcher Logic (Extended with full menu)
    const translations = {
        es: {
            "nav-home": "Inicio",
            "nav-about": "Nosotros",
            "nav-menu": "Carta",
            "nav-specialties": "Especialidades",
            "nav-location": "Ubicación",
            "nav-book": "Reservar",
            "tab-food": "Comidas",
            "tab-drinks": "Bebidas",
            "menu-cat-soft-drinks": "REFRESCOS",
            "menu-cat-beers": "CERVEZAS",
            "menu-cat-generous": "VINOS GENEROSOS",
            "menu-cat-mixed": "COMBINADOS",
            "menu-cat-bottles": "VINOS (BOTELLAS)",
            "menu-subcat-bottles": "BOTELLAS",
            "menu-cat-glass-wine": "VINOS POR COPA",
            "drink-tintos": "TINTOS",
            "drink-blancos": "BLANCOS",
            "drink-rosados": "ROSADOS",
            "drink-espumosos": "ESPUMOSOS",
            "drink-subcategory-rioja": "RIOJA",
            "drink-subcategory-ribera": "RIBERA DEL DUERO",
            "drink-subcategory-malaga": "VINOS DE MÁLAGA (RONDA)",
            "drink-water": "Agua 50cl",
            "drink-sparkling-water": "Agua con gas",
            "drink-juices": "Zumos (Manzana, Naranja, Melocotón, Piña)",
            "drink-sodas": "Refrescos (Coca Cola, Fanta, Tonica, Sprite, Ginger Ale)",
            "drink-nestea": "Nestea, Aquarius",
            "drink-tinto-verano": "Tinto de Verano",
            "drink-sangria-glass": "Copa de Sangría",
            "drink-sangria-cava-glass": "Copa Sangría Cava",
            "drink-aperol": "Aperol Spritz",
            "drink-sangria-pitcher": "Jarra de Sangría",
            "drink-sangria-cava-pitcher": "Jarra de Sangría Cava",
            "drink-montana-crianza": "Rioja Montaña Crianza",
            "drink-arienzo-crianza": "Rioja Arienzo Crianza",
            "drink-ribera-4": "Ribera 4 Meses",
            "drink-ribera-8": "Ribera 8 Meses",
            "drink-verdejo": "Verdejo",
            "drink-chardonnay": "Chardonnay",
            "drink-albarino": "Albariño",
            "drink-sauvignon": "Sauvignon Blanc",
            "drink-cava-glass": "Copa de Cava",
            "drink-mahou-cana": "Mahou 5 Estrellas (Caña 33cl)",
            "drink-jarra-50": "Jarra 50cl",
            "drink-radler": "Radler",
            "drink-mahou-00": "Mahou Tostada 0,0",
            "drink-mahou-gluten": "Mahou Sin Gluten",
            "drink-mahou-filtrar": "Mahou Sin Filtrar",
            "drink-alhambra-1925": "Alhambra Reserva 1925",
            "drink-manzanilla": "Copa de Manzanilla",
            "drink-tio-pepe": "Copa de Tio Pepe",
            "drink-palo-cortado": "Copa Palo Cortado",
            "drink-oloroso": "Copa Oloroso",
            "drink-amontillado": "Copa Amontillado",
            "drink-vermut": "Vermut",
            "drink-licor": "Licor",
            "drink-larios": "Larios",
            "drink-beefeater": "Beefeater",
            "drink-bombay": "Bombay Sapphire",
            "drink-tanqueray": "Tanqueray",
            "drink-hendricks": "Hendricks",
            "drink-jw": "Johnnie Walker",
            "drink-white-label": "White Label",
            "drink-ballantines": "Ballantines",
            "drink-jb": "J&B",
            "drink-cardhu": "Cardhu",
            "drink-barcelo": "Barceló",
            "drink-cacique": "Cacique",
            "drink-negrita": "Negrita",
            "drink-legendario": "Legendario",
            "drink-bacardi": "Bacardí",
            "drink-montana-casa": "Montaña Crianza 75cl (De la casa)",
            "drink-arienzo-riscal": "Arienzo de Marques de Riscal Crianza 75cl",
            "drink-ramon-bilbao": "Ramón Bilbao Crianza 75cl",
            "drink-diaz-bayo-4": "Diaz Bayo 4 Meses (De la casa) 75cl",
            "drink-diaz-bayo-8": "Diaz Bayo 8 Meses 75cl",
            "drink-pruno": "Pruno Finca Villacreces 75cl",
            "drink-rodero-crianza": "Carmelo Rodero Crianza 75cl",
            "drink-rodero-reserva": "Carmelo Rodero Reserva 75cl",
            "drink-lunares": "Lunares Tinto Roble",
            "drink-rueda-verdejo": "Rueda Verdejo (De la casa) 75cl",
            "drink-albarino-olma": "Albariño (Finca la Olma) 75cl",
            "drink-condes-albarei": "Condes de Albarei",
            "drink-chardonnay-laus": "Chardonnay (Laus) 75cl",
            "drink-sauvignon-diez": "Sauvignon Blanc (Diez Siglos) 75cl",
            "drink-godello": "Godello (Baron do Sil) 75cl",
            "drink-vivanco-blanco": "Vivanco (Lias Finas) 75cl",
            "drink-clavellina": "Clavellina Syrah 75cl",
            "drink-vivanco-rosado": "Vivanco (Rosé Lías Finas) 75cl",
            "drink-cava-botella": "Botella de Cava (Brut Nature) 75cl",
            "drink-marques-concordia": "Marques de la Concordia (Reserva)",
            "drink-moet": "Moët-Chandon 75cl",
            "drink-cava-rosado-botella": "Botella de Cava Rosado 75cl",
            "hero-title-1": "La Excelencia en cada Detalle",
            "hero-desc-1": "Una experiencia sensorial que redefine la alta cocina contemporánea en el corazón de Marbella.",
            "hero-cta": "Explorar Especialidades",
            "hero-title-2": "Sabor que Inspira",
            "hero-desc-2": "Ingredientes locales seleccionados para crear obras maestras culinarias en un ambiente único.",
            "hero-cta-2": "Ver la Carta",
            "about-subtitle": "Nuestra Herencia",
            "about-title": "Pasión por la Gastronomía",
            "about-p1": "En El Patio Antiguo, creemos que la cocina es un arte que se vive con los cinco sentidos. Nuestra historia comenzó con el deseo de fusionar las técnicas tradicionales con la innovación más vanguardista.",
            "about-p2": "Cada plato es una narrativa, un viaje a través de los sabores más puros y las texturas más sofisticadas. Bajo la dirección de nuestro equipo, buscamos la perfección en cada bocado.",
            "about-cta": "Descubrir Menú",
            "menu-subtitle": "Nuestra Propuesta",
            "menu-title": "Carta",
            "menu-cat-tapas": "Tapas",
            "menu-cat-tostas": "Tostas",
            "menu-cat-starters": "Entrantes",
            "menu-cat-salads": "Ensaladas",
            "menu-cat-fish": "Pescados",
            "menu-cat-meat": "Carnes",
            "menu-cat-desserts": "Postres",
            "menu-media": "Media",
            "menu-entera": "Ración",
            "spec-subtitle": "Selección del Chef",
            "spec-title": "Nuestras Especialidades",
            "spec-1-name": "Salmorejo Cordobés",
            "spec-1-desc": "Crema fría de tomates seleccionados, huevo y virutas de jamón ibérico.",
            "spec-2-name": "Albóndigas en Salsa",
            "spec-2-desc": "Receta tradicional con carne seleccionada y patatas fritas caseras.",
            "spec-3-name": "Crepe con Helado",
            "spec-3-desc": "Fina masa de crepe rellena, acompañada de helado de vainilla y chocolate.",
            "reviews-subtitle": "Servicio al Cliente",
            "reviews-title": "Lo que dicen nuestros clientes",
            "reviews-cta": "Ver todas las reseñas",
            "loc-subtitle": "Encuéntranos",
            "loc-title": "Ubicación & Contacto",
            "loc-hours": "Abierto todos los días: 12:00 - 00:00",
            "service-subtitle": "Excelencia y Calidez",
            "service-title": "Nuestro Servicio",
            "service-p1": "Nos enorgullecemos de ofrecer una atención al cliente excepcional. Nuestro equipo está dedicado a hacer que cada visita sea especial, brindando un servicio atento, profesional y cercano.",
            "service-p2": "Desde el momento en que cruza nuestra puerta, nuestro objetivo es que se sienta como en casa, disfrutando de un ambiente acogedor y una atención personalizada que cuida hasta el más mínimo detalle.",
            // Dishes
            "dish-alcachofa": "Alcachofa confitada",
            "dish-tortilla": "Tortilla española",
            "dish-morcilla": "Morcilla de Burgos con pimientos",
            "dish-queso-cabra": "Queso de cabra sobre tosta de aceite",
            "dish-chistorra": "Chistorra",
            "dish-ensaladilla": "Ensaladilla rusa",
            "dish-tequenos": "Tequeños",
            "dish-albondigas": "Albóndigas de ternera con patatas fritas",
            "dish-torrezno": "Torrezno de Soria con guacamole",
            "dish-cerdo-salsa": "Carne de cerdo en salsa",
            "dish-bravas": "Patatas bravas",
            "dish-tortillita-camarones": "Tortillita de camarones",
            "dish-brocheta-gambas": "Brocheta de gambas",
            "dish-mini-hamburguesa": "Mini hamburguesa especial",
            "dish-bao-carrillada": "Bao de carrillada",
            "dish-tartar-atun": "Taco de tartar de atún con wakame",
            "dish-patatas-fritas": "Patatas fritas",
            "tosta-payoyo": "Queso payoyo, tomate y sardina ahumada",
            "tosta-manchego": "Crema de manchego con jamón ibérico",
            "tosta-bacalao": "Bacalao ahumado con tomate natural",
            "tosta-sardina": "Sardina ahumada con tomate natural",
            "tosta-camembert": "Crema camembert con jamón ibérico",
            "tosta-brie": "Queso brie con cebolla caramelizada",
            "tosta-iberico": "Jamón ibérico",
            "tosta-salmon": "Queso crema con salmón ahumado",
            "tosta-mechada": "Carne mechada con tomate natural",
            "starter-boquerones": "Boquerones en vinagre",
            "starter-carpaccio": "Carpaccio de chuleta con parmesano",
            "starter-padron": "Pimientos de Padrón",
            "starter-croquetas-rabo": "Croquetas de rabo de toro",
            "starter-croquetas-jamon": "Croquetas de jamón ibérico",
            "starter-croquetas-variadas": "Croquetas variadas (8 uds)",
            "starter-croquetas-variadas-desc": "Jamón, rabo de toro, cochinita con manzana y calabaza con parmesano",
            "starter-anchoas": "Anchoas del Cantábrico",
            "starter-quesos": "Tabla de quesos variados",
            "starter-huevos-rotos": "Huevos rotos con jamón ibérico",
            "starter-jamon": "Jamón ibérico",
            "starter-lomo": "Caña de lomo ibérico",
            "starter-surtido": "Surtido ibérico completo",
            "starter-chorizo": "Chorizo ibérico",
            "starter-salchichon": "Salchichón ibérico",
            "starter-manchego": "Queso puro manchego",
            "starter-payoyo": "Queso payoyo",
            "starter-camembert": "Queso Camembert frito",
            "salad-gazpacho": "Gazpacho andaluz",
            "salad-salmorejo": "Salmorejo cordobés",
            "salad-queso-cabra": "Ensalada de queso de cabra",
            "salad-tomate-simple": "Tomate aliñado",
            "salad-tomate": "Tomate aliñado con ventresca",
            "salad-burratina": "Ensalada de burratina",
            "salad-patio": "Ensalada El Patio Antiguo",
            "fish-mejillones": "Mejillones a la bearnesa",
            "fish-salmon": "Salmón a la parrilla",
            "fish-pulpo": "Pulpo a la gallega",
            "fish-pulpo-parrilla": "Medio pulpo a la parrilla con puré de patatas",
            "fish-pez-espada": "Pez espada a la parrilla",
            "fish-pilpil": "Gambas al pil pil",
            "fish-almejas": "Almejas al ajillo",
            "fish-calamar": "Calamar nacional a la parrilla",
            "meat-rabo-toro": "Milhojas de rabo de toro",
            "meat-cordero": "Chuletitas de cordero lechal",
            "meat-entrecot": "Entrecot de buey (350 g)",
            "meat-chuleton": "Chuletón de vaca (850 g)",
            "meat-secreto": "Secreto ibérico de bellota",
            "meat-carrillada": "Carrillada en salsa syrah",
            "meat-costilla-ternera": "Costilla de ternera asada",
            "meat-costilla-cerdo": "Costilla de cerdo a la barbacoa",
            "dessert-coulant": "Coulant de chocolate",
            "dessert-brownie": "Brownie con helado de vainilla",
            "dessert-manzana": "Tartaleta de manzana con helado",
            "dessert-helado": "Helado vainilla-chocolate",
            "dessert-crepes": "Crepes con nutella y helado",
            "dessert-tarta-queso": "Tarta de queso con pistacho"
        },
        en: {
            "nav-home": "Home",
            "nav-about": "About Us",
            "nav-menu": "Menu",
            "nav-specialties": "Specialties",
            "nav-location": "Location",
            "nav-book": "Book Now",
            "tab-food": "Food",
            "tab-drinks": "Drinks",
            "menu-cat-soft-drinks": "SOFT DRINKS",
            "menu-cat-beers": "BEERS",
            "menu-cat-generous": "GENEROUS WINES",
            "menu-cat-mixed": "MIXED DRINKS",
            "menu-cat-bottles": "WINES (BOTTLES)",
            "menu-subcat-bottles": "BOTTLES",
            "menu-cat-glass-wine": "WINES BY THE GLASS",
            "drink-tintos": "RED WINE",
            "drink-blancos": "WHITE WINE",
            "drink-rosados": "ROSÉ WINE",
            "drink-espumosos": "SPARKLING",
            "drink-subcategory-rioja": "RIOJA",
            "drink-subcategory-ribera": "RIBERA DEL DUERO",
            "drink-subcategory-malaga": "MÁLAGA WINES (RONDA)",
            "drink-water": "Water 50cl",
            "drink-sparkling-water": "Sparkling water",
            "drink-juices": "Juices (Apple, Orange, Peach, Pineapple)",
            "drink-sodas": "Soft drinks (Coca Cola, Fanta, Tonica, Sprite, Ginger Ale)",
            "drink-nestea": "Nestea, Aquarius",
            "drink-tinto-verano": "Wine Spritzer",
            "drink-sangria-glass": "Sangría Glass",
            "drink-sangria-cava-glass": "Cava Sangría Glass",
            "drink-aperol": "Aperol Spritz",
            "drink-sangria-pitcher": "Sangría Pitcher",
            "drink-sangria-cava-pitcher": "Cava Sangría Pitcher",
            "drink-montana-crianza": "Rioja Montaña Crianza",
            "drink-arienzo-crianza": "Rioja Arienzo Crianza",
            "drink-ribera-4": "Ribera 4 Months",
            "drink-ribera-8": "Ribera 8 Months",
            "drink-verdejo": "Verdejo",
            "drink-chardonnay": "Chardonnay",
            "drink-albarino": "Albariño",
            "drink-sauvignon": "Sauvignon Blanc",
            "drink-cava-glass": "Glass of Cava",
            "drink-mahou-cana": "Mahou 5 Stars (Glass 33cl)",
            "drink-jarra-50": "Pitcher 50cl",
            "drink-radler": "Radler",
            "drink-mahou-00": "Mahou Toasted 0,0",
            "drink-mahou-gluten": "Gluten-Free Mahou",
            "drink-mahou-filtrar": "Unfiltered Mahou",
            "drink-alhambra-1925": "Alhambra Reserva 1925",
            "drink-manzanilla": "Manzanilla Glass",
            "drink-tio-pepe": "Tio Pepe Glass",
            "drink-palo-cortado": "Palo Cortado Glass",
            "drink-oloroso": "Oloroso Glass",
            "drink-amontillado": "Amontillado Glass",
            "drink-vermut": "Vermouth",
            "drink-licor": "Liquor",
            "drink-larios": "Larios",
            "drink-beefeater": "Beefeater",
            "drink-bombay": "Bombay Sapphire",
            "drink-tanqueray": "Tanqueray",
            "drink-hendricks": "Hendricks",
            "drink-jw": "Johnnie Walker",
            "drink-white-label": "White Label",
            "drink-ballantines": "Ballantines",
            "drink-jb": "J&B",
            "drink-cardhu": "Cardhu",
            "drink-barcelo": "Barceló",
            "drink-cacique": "Cacique",
            "drink-negrita": "Negrita",
            "drink-legendario": "Legendario",
            "drink-bacardi": "Bacardí",
            "drink-montana-casa": "Montaña Crianza 75cl (House Wine)",
            "drink-arienzo-riscal": "Arienzo Marques de Riscal Crianza 75cl",
            "drink-ramon-bilbao": "Ramón Bilbao Crianza 75cl",
            "drink-diaz-bayo-4": "Diaz Bayo 4 Months (House Wine) 75cl",
            "drink-diaz-bayo-8": "Diaz Bayo 8 Months 75cl",
            "drink-pruno": "Pruno Finca Villacreces 75cl",
            "drink-rodero-crianza": "Carmelo Rodero Crianza 75cl",
            "drink-rodero-reserva": "Carmelo Rodero Reserva 75cl",
            "drink-lunares": "Lunares Tinto Roble",
            "drink-rueda-verdejo": "Rueda Verdejo (House Wine) 75cl",
            "drink-albarino-olma": "Albariño (Finca la Olma) 75cl",
            "drink-condes-albarei": "Condes de Albarei",
            "drink-chardonnay-laus": "Chardonnay (Laus) 75cl",
            "drink-sauvignon-diez": "Sauvignon Blanc (Diez Siglos) 75cl",
            "drink-godello": "Godello (Baron do Sil) 75cl",
            "drink-vivanco-blanco": "Vivanco (Lias Finas) 75cl",
            "drink-clavellina": "Clavellina Syrah 75cl",
            "drink-vivanco-rosado": "Vivanco (Rosé Lías Finas) 75cl",
            "drink-cava-botella": "Bottle of Cava (Brut Nature) 75cl",
            "drink-marques-concordia": "Marques de la Concordia (Reserva)",
            "drink-moet": "Moët-Chandon 75cl",
            "drink-cava-rosado-botella": "Bottle of Rosé Cava 75cl",
            "hero-title-1": "Excellence in Every Detail",
            "hero-desc-1": "A sensory experience that redefines contemporary haute cuisine in the heart of Marbella.",
            "hero-cta": "Explore Specialties",
            "hero-title-2": "Flavor that Inspires",
            "hero-desc-2": "Selected local ingredients to create culinary masterpieces in a unique atmosphere.",
            "hero-cta-2": "View Menu",
            "about-subtitle": "Our Heritage",
            "about-title": "Passion for Gastronomy",
            "about-p1": "At El Patio Antiguo, we believe cooking is an art lived with all five senses. Our history began with a desire to merge traditional techniques with avant-garde innovation.",
            "about-p2": "Each dish is a narrative, a journey through the purest flavors and most sophisticated textures. Led by our team, we seek perfection in every bite.",
            "about-cta": "Discover Menu",
            "menu-subtitle": "Our Proposal",
            "menu-title": "Menu",
            "menu-cat-tapas": "Tapas",
            "menu-cat-tostas": "Toasted Bread",
            "menu-cat-starters": "Starters",
            "menu-cat-salads": "Salads",
            "menu-cat-fish": "Fish",
            "menu-cat-meat": "Meat",
            "menu-cat-desserts": "Desserts",
            "menu-media": "Half",
            "menu-entera": "Full",
            "spec-subtitle": "Chef's Selection",
            "spec-title": "Our Specialties",
            "spec-1-name": "Cordobés Salmorejo",
            "spec-1-desc": "Cold cream of selected tomatoes, egg, and Iberian ham shavings.",
            "spec-2-name": "Meatballs in Sauce",
            "spec-2-desc": "Traditional recipe with selected meat and homemade fries.",
            "spec-3-name": "Crepe with Ice Cream",
            "spec-3-desc": "Thin filled crepe dough, served with vanilla and chocolate ice cream.",
            "reviews-subtitle": "Customer Service",
            "reviews-title": "What our customers say",
            "reviews-cta": "See all reviews",
            "loc-subtitle": "Find Us",
            "loc-title": "Location & Contact",
            "loc-hours": "Open every day: 12:00 - 00:00",
            "service-subtitle": "Excellence and Warmth",
            "service-title": "Our Service",
            "service-p1": "We pride ourselves on offering exceptional customer service. Our team is dedicated to making every visit special, providing attentive, professional, and friendly service.",
            "service-p2": "From the moment you walk through our door, our goal is to make you feel at home, enjoying a welcoming atmosphere and personalized attention that looks after every single detail.",
            // Dishes
            "dish-alcachofa": "Confit Artichoke",
            "dish-tortilla": "Spanish Omelette",
            "dish-morcilla": "Burgos Blood Sausage with Peppers",
            "dish-queso-cabra": "Goat Cheese on Oil Toast",
            "dish-chistorra": "Chistorra Sausage",
            "dish-ensaladilla": "Russian Salad",
            "dish-tequenos": "Tequeños (Cheese Sticks)",
            "dish-albondigas": "Veal Meatballs with French Fries",
            "dish-torrezno": "Soria Pork Rind with Guacamole",
            "dish-cerdo-salsa": "Pork in Sauce",
            "dish-bravas": "Spicy 'Bravas' Potatoes",
            "dish-tortillita-camarones": "Shrimp Fritters",
            "dish-brocheta-gambas": "Prawn Skewer",
            "dish-mini-hamburguesa": "Special Mini Burger",
            "dish-bao-carrillada": "Pork Cheek Bao",
            "dish-tartar-atun": "Tuna Tartare Taco with Wakame",
            "dish-patatas-fritas": "French Fries",
            "tosta-payoyo": "Payoyo Cheese, Tomato, and Smoked Sardine",
            "tosta-manchego": "Manchego Cream with Iberian Ham",
            "tosta-bacalao": "Smoked Cod with Fresh Tomato",
            "tosta-sardina": "Smoked Sardine with Fresh Tomato",
            "tosta-camembert": "Camembert Cream with Iberian Ham",
            "tosta-brie": "Brie Cheese with Caramelized Onion",
            "tosta-iberico": "Iberian Ham",
            "tosta-salmon": "Cream Cheese with Smoked Salmon",
            "tosta-mechada": "Shredded Meat with Fresh Tomato",
            "starter-boquerones": "Anchovies in Vinegar",
            "starter-carpaccio": "Steak Carpaccio with Parmesan",
            "starter-padron": "Padrón Peppers",
            "starter-croquetas-rabo": "Oxtail Croquettes",
            "starter-croquetas-jamon": "Iberian Ham Croquettes",
            "starter-croquetas-variadas": "Assorted Croquettes (8 pcs)",
            "starter-croquetas-variadas-desc": "Ham, oxtail, suckling pig with apple, and pumpkin with parmesan",
            "starter-anchoas": "Cantabrian Anchovies",
            "starter-quesos": "Mixed Cheese Board",
            "starter-huevos-rotos": "Broken Eggs with Iberian Ham",
            "starter-jamon": "Iberian Ham",
            "starter-lomo": "Iberian Loin (Caña de Lomo)",
            "starter-surtido": "Complete Iberian Assortment",
            "starter-chorizo": "Iberian Chorizo",
            "starter-salchichon": "Iberian Salchichón",
            "starter-manchego": "Pure Manchego Cheese",
            "starter-payoyo": "Payoyo Cheese",
            "starter-camembert": "Fried Camembert Cheese",
            "salad-gazpacho": "Andalusian Gazpacho",
            "salad-salmorejo": "Cordobés Salmorejo",
            "salad-queso-cabra": "Goat Cheese Salad",
            "salad-tomate-simple": "Seasoned Tomato",
            "salad-tomate": "Seasoned Tomato with Tuna Belly",
            "salad-burratina": "Burratina Salad",
            "salad-patio": "El Patio Antiguo Salad",
            "fish-mejillones": "Mussels with Bearnaise Sauce",
            "fish-salmon": "Grilled Salmon",
            "fish-pulpo": "Galician Style Octopus",
            "fish-pulpo-parrilla": "Half Grilled Octopus with Mashed Potatoes",
            "fish-pez-espada": "Grilled Swordfish",
            "fish-pilpil": "Prawns Pil Pil",
            "fish-almejas": "Garlic Clams",
            "fish-calamar": "National Grilled Squid",
            "meat-rabo-toro": "Oxtail Mille-feuille",
            "meat-cordero": "Suckling Lamb Chops",
            "meat-entrecot": "Beef Entrecote (350 g)",
            "meat-chuleton": "Beef Ribeye (850 g)",
            "meat-secreto": "Acorn-fed Iberian 'Secreto'",
            "meat-carrillada": "Pork Cheeks in Syrah Sauce",
            "meat-costilla-ternera": "Roasted Veal Rib",
            "meat-costilla-cerdo": "BBQ Pork Ribs",
            "dessert-coulant": "Chocolate Coulant",
            "dessert-brownie": "Brownie with Vanilla Ice Cream",
            "dessert-manzana": "Apple Tartlet with Ice Cream",
            "dessert-helado": "Vanilla-Chocolate Ice Cream",
            "dessert-crepes": "Crepes with Nutella and Ice Cream",
            "dessert-tarta-queso": "Pistachio Cheesecake"
        },
        fr: {
            "nav-home": "Accueil",
            "nav-about": "À Propos",
            "nav-menu": "Carta",
            "nav-specialties": "Spécialités",
            "nav-location": "Emplacement",
            "nav-book": "Réserver",
            "tab-food": "Plats",
            "tab-drinks": "Boissons",
            "menu-cat-soft-drinks": "RAFRAÎCHISSEMENTS",
            "menu-cat-beers": "BIÈRES",
            "menu-cat-generous": "VINS GÉNÉREUX",
            "menu-cat-mixed": "BOISSONS MIXTURES",
            "menu-cat-bottles": "VINS (BOUTEILLES)",
            "menu-subcat-bottles": "BOUTEILLES",
            "menu-cat-glass-wine": "VINS AU VERRE",
            "drink-tintos": "VINS ROUGES",
            "drink-blancos": "VINS BLANCS",
            "drink-rosados": "VINS ROSÉS",
            "drink-espumosos": "EFFERVESCENTS",
            "drink-subcategory-rioja": "RIOJA",
            "drink-subcategory-ribera": "RIBERA DEL DUERO",
            "drink-subcategory-malaga": "VINS DE MALAGA (RONDA)",
            "drink-water": "Eau 50cl",
            "drink-sparkling-water": "Eau gazeuse",
            "drink-juices": "Jus (Pomme, Orange, Pêche, Ananas)",
            "drink-sodas": "Sodas (Coca Cola, Fanta, Tonica, Sprite, Ginger Ale)",
            "drink-nestea": "Nestea, Aquarius",
            "drink-tinto-verano": "Tinto de Verano",
            "drink-sangria-glass": "Verre de Sangría",
            "drink-sangria-cava-glass": "Verre de Sangría Cava",
            "drink-aperol": "Aperol Spritz",
            "drink-sangria-pitcher": "Carafe de Sangría",
            "drink-sangria-cava-pitcher": "Carafe de Sangría Cava",
            "drink-montana-crianza": "Rioja Montaña Crianza",
            "drink-arienzo-crianza": "Rioja Arienzo Crianza",
            "drink-ribera-4": "Ribera 4 Mois",
            "drink-ribera-8": "Ribera 8 Mois",
            "drink-verdejo": "Verdejo",
            "drink-chardonnay": "Chardonnay",
            "drink-albarino": "Albariño",
            "drink-sauvignon": "Sauvignon Blanc",
            "drink-cava-glass": "Verre de Cava",
            "drink-mahou-cana": "Mahou 5 Étoiles (Demi 33cl)",
            "drink-jarra-50": "Chope 50cl",
            "drink-radler": "Radler",
            "drink-mahou-00": "Mahou Grillée 0,0",
            "drink-mahou-gluten": "Mahou Sans Gluten",
            "drink-mahou-filtrar": "Mahou Non Filtrée",
            "drink-alhambra-1925": "Alhambra Reserva 1925",
            "drink-manzanilla": "Verre de Manzanilla",
            "drink-tio-pepe": "Verre de Tio Pepe",
            "drink-palo-cortado": "Verre de Palo Cortado",
            "drink-oloroso": "Verre d'Oloroso",
            "drink-amontillado": "Verre d'Amontillado",
            "drink-vermut": "Vermouth",
            "drink-licor": "Liqueur",
            "drink-larios": "Larios",
            "drink-beefeater": "Beefeater",
            "drink-bombay": "Bombay Sapphire",
            "drink-tanqueray": "Tanqueray",
            "drink-hendricks": "Hendricks",
            "drink-jw": "Johnnie Walker",
            "drink-white-label": "White Label",
            "drink-ballantines": "Ballantines",
            "drink-jb": "J&B",
            "drink-cardhu": "Cardhu",
            "drink-barcelo": "Barceló",
            "drink-cacique": "Cacique",
            "drink-negrita": "Negrita",
            "drink-legendario": "Legendario",
            "drink-bacardi": "Bacardí",
            "drink-montana-casa": "Montaña Crianza 75cl (Vin de la Maison)",
            "drink-arienzo-riscal": "Arienzo de Marques de Riscal Crianza 75cl",
            "drink-ramon-bilbao": "Ramón Bilbao Crianza 75cl",
            "drink-diaz-bayo-4": "Diaz Bayo 4 Mois (Vin de la Maison) 75cl",
            "drink-diaz-bayo-8": "Diaz Bayo 8 Mois 75cl",
            "drink-pruno": "Pruno Finca Villacreces 75cl",
            "drink-rodero-crianza": "Carmelo Rodero Crianza 75cl",
            "drink-rodero-reserva": "Carmelo Rodero Reserva 75cl",
            "drink-lunares": "Lunares Tinto Roble",
            "drink-rueda-verdejo": "Rueda Verdejo (Vin de la Maison) 75cl",
            "drink-albarino-olma": "Albariño (Finca la Olma) 75cl",
            "drink-condes-albarei": "Condes de Albarei",
            "drink-chardonnay-laus": "Chardonnay (Laus) 75cl",
            "drink-sauvignon-diez": "Sauvignon Blanc (Diez Siglos) 75cl",
            "drink-godello": "Godello (Baron do Sil) 75cl",
            "drink-vivanco-blanco": "Vivanco (Lias Finas) 75cl",
            "drink-clavellina": "Clavellina Syrah 75cl",
            "drink-vivanco-rosado": "Vivanco (Rosé Lías Finas) 75cl",
            "drink-cava-botella": "Bouteille de Cava (Brut Nature) 75cl",
            "drink-marques-concordia": "Marques de la Concordia (Reserva)",
            "drink-moet": "Moët-Chandon 75cl",
            "drink-cava-rosado-botella": "Bouteille de Cava Rosé 75cl",
            "hero-title-1": "L'Excellence dans chaque Détail",
            "hero-desc-1": "Une expérience sensorielle qui redéfinit la haute cuisine contemporaine au cœur de Marbella.",
            "hero-cta": "Explorer les Spécialités",
            "hero-title-2": "Saveur qui Inspire",
            "hero-desc-2": "Ingrédients locaux sélectionnés pour créer des chefs-d'œuvre culinaires dans une ambiance unique.",
            "hero-cta-2": "Voir la Carta",
            "about-subtitle": "Notre Héritage",
            "about-title": "Passion pour la Gastronomية",
            "about-p1": "Chez El Patio Antiguo, nous pensons que la cuisine est un art qui se vit avec les cinq sens. Notre histoire a commencé par le désir de fusionner les techniques traditionnelles avec l'innovation d'avant-garde.",
            "about-p2": "Chaque plat est un récit, un voyage à travers les saveurs les plus pures et les textures les plus sophistiquées. Sous la direction de nuestro equipo, nous recherchons la perfection dans chaque bouchée.",
            "about-cta": "Découvrir le Menu",
            "menu-subtitle": "Notre Proposition",
            "menu-title": "Carta",
            "menu-cat-tapas": "Tapas",
            "menu-cat-tostas": "Tartines",
            "menu-cat-starters": "Entrées",
            "menu-cat-salads": "Salades",
            "menu-cat-fish": "Poissons",
            "menu-cat-meat": "Viandes",
            "menu-cat-desserts": "Desserts",
            "menu-media": "Demi",
            "menu-entera": "Plat",
            "spec-subtitle": "Sélection du Chef",
            "spec-title": "Nos Spécialités",
            "spec-1-name": "Salmorejo de Cordoue",
            "spec-1-desc": "Crème froide de tomates sélectionnées, œuf et copeaux de jambon ibérique.",
            "spec-2-name": "Boulettes en Sauce",
            "spec-2-desc": "Recette traditionnelle avec de la viande sélectionnée et des frites maison.",
            "spec-3-name": "Crêpe avec Glace",
            "spec-3-desc": "Fine pâte à crêpe fourrée, servie avec glace vanille et chocolat.",
            "reviews-subtitle": "Service Client",
            "reviews-title": "Ce que disent nos clients",
            "reviews-cta": "Voir tous les avis",
            "loc-subtitle": "Nous Trouver",
            "loc-title": "Lieu & Contact",
            "loc-hours": "Ouvert tous les jours: 12:00 - 00:00",
            "service-subtitle": "Excellence et Chaleur",
            "service-title": "Notre Service",
            "service-p1": "Nous sommes fiers d'offrir un service client exceptionnel. Notre équipe se consacre à rendre chaque visite spéciale, en offrant un service attentif, professionnel et amical.",
            "service-p2": "Dès l'instant où vous franchissez notre porte, notre objectif est de vous faire sentir comme chez vous, en profitant d'une atmosphère accueillante et d'une attention personnalisée qui soigne chaque détail.",
            // Dishes
            "dish-alcachofa": "Artichaut confit",
            "dish-tortilla": "Omelette espagnole",
            "dish-morcilla": "Boudin de Burgos aux poivrons",
            "dish-queso-cabra": "Fromage de chèvre sur tartine à l'huile",
            "dish-chistorra": "Saucisse Chistorra",
            "dish-ensaladilla": "Salade russe",
            "dish-tequenos": "Tequeños (Bâtonnets de fromage)",
            "dish-albondigas": "Boulettes de veau avec frites",
            "dish-torrezno": "Graton de Soria au guacamole",
            "dish-cerdo-salsa": "Porc en sauce",
            "dish-bravas": "Pommes de terre 'Bravas'",
            "dish-tortillita-camarones": "Galettes de crevettes",
            "dish-brocheta-gambas": "Brochette de crevettes",
            "dish-mini-hamburguesa": "Mini burger spécial",
            "dish-bao-carrillada": "Bao de joue de porc",
            "dish-tartar-atun": "Taco au tartare de thon et wakame",
            "dish-patatas-fritas": "Frites",
            "tosta-payoyo": "Fromage Payoyo, tomate et sardine fumée",
            "tosta-manchego": "Crème de Manchego avec jambon ibérique",
            "tosta-bacalao": "Cabillaud fumé avec tomate fraîche",
            "tosta-sardina": "Sardine fumée avec tomate fraîche",
            "tosta-camembert": "Crème de camembert avec jambon ibérique",
            "tosta-brie": "Fromage brie avec oignon caramélisé",
            "tosta-iberico": "Jambon ibérique",
            "tosta-salmon": "Fromage à la crème avec saumon fumé",
            "tosta-mechada": "Viande effilochée avec tomate fraîche",
            "starter-boquerones": "Anchois au vinaigre",
            "starter-carpaccio": "Carpaccio de bœuf au parmesan",
            "starter-padron": "Poivrons de Padrón",
            "starter-croquetas-rabo": "Croquettes de queue de bœuf",
            "starter-croquetas-jamon": "Croquettes de jambon ibérique",
            "starter-croquetas-variadas": "Assortiment de croquettes (8 pcs)",
            "starter-croquetas-variadas-desc": "Jambon, queue de bœuf, cochon de lait à la pomme et citrouille au parmesan",
            "starter-anchoas": "Anchois de Cantabrie",
            "starter-quesos": "Plateau de fromages variés",
            "starter-huevos-rotos": "Œufs cassés au jambon ibérique",
            "starter-jamon": "Jambon ibérique",
            "starter-lomo": "Longe ibérique (Caña de Lomo)",
            "starter-surtido": "Assortiment ibérique complet",
            "starter-chorizo": "Chorizo ibérique",
            "starter-salchichon": "Saucisson ibérique",
            "starter-manchego": "Fromage pur Manchego",
            "starter-payoyo": "Fromage Payoyo",
            "starter-camembert": "Fromage Camembert frit",
            "salad-gazpacho": "Gaspacho andalou",
            "salad-salmorejo": "Salmorejo de Cordoue",
            "salad-queso-cabra": "Salade de fromage de chèvre",
            "salad-tomate-simple": "Tomate assaisonnée",
            "salad-tomate": "Tomate assaisonnée à la ventrèche de thon",
            "salad-burratina": "Salade de burratina",
            "salad-patio": "Salade El Patio Antiguo",
            "fish-mejillones": "Moules à la sauce béarnaise",
            "fish-salmon": "Saumon grillé",
            "fish-pulpo": "Poulpe à la galicienne",
            "fish-pulpo-parrilla": "Demi poulpe grillé avec purée de pommes de terre",
            "fish-pez-espada": "Espadon grillé",
            "fish-pilpil": "Crevettes au Pil Pil",
            "fish-almejas": "Palourdes à l'ail",
            "fish-calamar": "Calmar national grillé",
            "meat-rabo-toro": "Mille-feuille de queue de bœuf",
            "meat-cordero": "Côtelettes d'agneau de lait",
            "meat-entrecot": "Entrecôte de bœuf (350 g)",
            "meat-chuleton": "Côte de bœuf (850 g)",
            "meat-secreto": "Secret ibérique de gland",
            "meat-carrillada": "Joues de porc à la sauce Syrah",
            "meat-costilla-ternera": "Côte de veau rôtie",
            "meat-costilla-cerdo": "Travers de porc au barbecue",
            "dessert-coulant": "Coulant au chocolat",
            "dessert-brownie": "Brownie avec glace vanille",
            "dessert-manzana": "Tartelette aux pommes avec glace",
            "dessert-helado": "Glace vanille-chocolat",
            "dessert-crepes": "Crêpes au Nutella et glace",
            "dessert-tarta-queso": "Cheesecake à la pistache"
        },
        de: {
            "nav-home": "Startseite",
            "nav-about": "Über uns",
            "nav-menu": "Karte",
            "nav-specialties": "Spezialitäten",
            "nav-location": "Standort",
            "nav-book": "Reservieren",
            "tab-food": "Speisen",
            "tab-drinks": "Getränke",
            "menu-cat-soft-drinks": "ERFRISCHUNGSGETRÄNKE",
            "menu-cat-beers": "BIERE",
            "menu-cat-generous": "SÜDWEINE",
            "menu-cat-mixed": "LONGDRINKS",
            "menu-cat-bottles": "WEINE (FLASCHEN)",
            "menu-subcat-bottles": "FLASCHEN",
            "menu-cat-glass-wine": "OFFENE WEINE",
            "drink-tintos": "ROTWEINE",
            "drink-blancos": "WEISSWEINE",
            "drink-rosados": "ROSÉWEINE",
            "drink-espumosos": "SCHAUMWEINE",
            "drink-subcategory-rioja": "RIOJA",
            "drink-subcategory-ribera": "RIBERA DEL DUERO",
            "drink-subcategory-malaga": "MALAGA WEINE (RONDA)",
            "drink-water": "Wasser 50cl",
            "drink-sparkling-water": "Mineralwasser",
            "drink-juices": "Säfte (Apfel, Orange, Pfirsich, Ananas)",
            "drink-sodas": "Erfrischungsgetränke (Coca Cola, Fanta, Tonica, Sprite, Ginger Ale)",
            "drink-nestea": "Nestea, Aquarius",
            "drink-tinto-verano": "Weinschorle",
            "drink-sangria-glass": "Glas Sangría",
            "drink-sangria-cava-glass": "Glas Sangría Cava",
            "drink-aperol": "Aperol Spritz",
            "drink-sangria-pitcher": "Krug Sangría",
            "drink-sangria-cava-pitcher": "Krug Sangría Cava",
            "drink-montana-crianza": "Rioja Montaña Crianza",
            "drink-arienzo-crianza": "Rioja Arienzo Crianza",
            "drink-ribera-4": "Ribera 4 Monate",
            "drink-ribera-8": "Ribera 8 Monate",
            "drink-verdejo": "Verdejo",
            "drink-chardonnay": "Chardonnay",
            "drink-albarino": "Albariño",
            "drink-sauvignon": "Sauvignon Blanc",
            "drink-cava-glass": "Glas Cava",
            "drink-mahou-cana": "Mahou 5 Sterne (Glas 33cl)",
            "drink-jarra-50": "Krug 50cl",
            "drink-radler": "Radler",
            "drink-mahou-00": "Mahou Getoastet 0,0",
            "drink-mahou-gluten": "Glutenfrei Mahou",
            "drink-mahou-filtrar": "Ungefiltert Mahou",
            "drink-alhambra-1925": "Alhambra Reserva 1925",
            "drink-manzanilla": "Glas Manzanilla",
            "drink-tio-pepe": "Glas Tio Pepe",
            "drink-palo-cortado": "Glas Palo Cortado",
            "drink-oloroso": "Glas Oloroso",
            "drink-amontillado": "Glas Amontillado",
            "drink-vermut": "Wermut",
            "drink-licor": "Likör",
            "drink-larios": "Larios",
            "drink-beefeater": "Beefeater",
            "drink-bombay": "Bombay Sapphire",
            "drink-tanqueray": "Tanqueray",
            "drink-hendricks": "Hendricks",
            "drink-jw": "Johnnie Walker",
            "drink-white-label": "White Label",
            "drink-ballantines": "Ballantines",
            "drink-jb": "J&B",
            "drink-cardhu": "Cardhu",
            "drink-barcelo": "Barceló",
            "drink-cacique": "Cacique",
            "drink-negrita": "Negrita",
            "drink-legendario": "Legendario",
            "drink-bacardi": "Bacardí",
            "drink-montana-casa": "Montaña Crianza 75cl (Hauswein)",
            "drink-arienzo-riscal": "Arienzo Marques de Riscal Crianza 75cl",
            "drink-ramon-bilbao": "Ramón Bilbao Crianza 75cl",
            "drink-diaz-bayo-4": "Diaz Bayo 4 Monate (Hauswein) 75cl",
            "drink-diaz-bayo-8": "Diaz Bayo 8 Monate 75cl",
            "drink-pruno": "Pruno Finca Villacreces 75cl",
            "drink-rodero-crianza": "Carmelo Rodero Crianza 75cl",
            "drink-rodero-reserva": "Carmelo Rodero Reserva 75cl",
            "drink-lunares": "Lunares Tinto Roble",
            "drink-rueda-verdejo": "Rueda Verdejo (Hauswein) 75cl",
            "drink-albarino-olma": "Albariño (Finca la Olma) 75cl",
            "drink-condes-albarei": "Condes de Albarei",
            "drink-chardonnay-laus": "Chardonnay (Laus) 75cl",
            "drink-sauvignon-diez": "Sauvignon Blanc (Diez Siglos) 75cl",
            "drink-godello": "Godello (Baron do Sil) 75cl",
            "drink-vivanco-blanco": "Vivanco (Lias Finas) 75cl",
            "drink-clavellina": "Clavellina Syrah 75cl",
            "drink-vivanco-rosado": "Vivanco (Rosé Lías Finas) 75cl",
            "drink-cava-botella": "Flasche Cava (Brut Nature) 75cl",
            "drink-marques-concordia": "Marques de la Concordia (Reserva)",
            "drink-moet": "Moët-Chandon 75cl",
            "drink-cava-rosado-botella": "Flasche Rosé Cava 75cl",
            "hero-title-1": "Exzellenz in jedem Detail",
            "hero-desc-1": "Ein sensorisches Erlebnis, das die zeitgenössische Haute Cuisine im Herzen von Marbella neu definiert.",
            "hero-cta": "Spezialitäten entdecken",
            "hero-title-2": "Geschmack, der inspiriert",
            "hero-desc-2": "Ausgewählte lokale Zutaten, um kulinarische Meisterwerke in einem einzigartigen Ambiente zu schaffen.",
            "hero-cta-2": "Speisekarte ansehen",
            "about-subtitle": "Unser Erbe",
            "about-title": "Leidenschaft für Gastronomie",
            "about-p1": "Bei El Patio Antiguo glauben wir, dass Kochen eine Kunst ist, die mit allen fūnf Sinnen gelebt wird. Unsere Geschichte begann mit dem Wunsch, traditionelle Techniken mit modernster Innovation zu verschmelzen.",
            "about-p2": "Jedes Gericht ist eine Erzählung, eine Reise durch die reinsten Aromen und anspruchsvollsten Texturen. Unter der Leitung unseres Teams streben wir nach Perfektion in jedem Bissen.",
            "about-cta": "Menü entdecken",
            "menu-subtitle": "Unser Angebot",
            "menu-title": "Speisekarte",
            "menu-cat-tapas": "Tapas",
            "menu-cat-tostas": "Tostas",
            "menu-cat-starters": "Vorspeisen",
            "menu-cat-salads": "Salate",
            "menu-cat-fish": "Fisch",
            "menu-cat-meat": "Fleisch",
            "menu-cat-desserts": "Desserts",
            "menu-media": "Halbe",
            "menu-entera": "Ganze",
            "spec-subtitle": "Auswahl des Küchenchefs",
            "spec-title": "Unsere Spezialitäten",
            "spec-1-name": "Salmorejo aus Córdoba",
            "spec-1-desc": "Kalte Creme aus ausgewählten Tomaten, Ei und ibirischen Schinkenspänen.",
            "spec-2-name": "Fleischbällchen in Sauce",
            "spec-2-desc": "Traditionelles Rezept mit ausgewähltem Fleisch und hausgemachten Pommes.",
            "spec-3-name": "Crepe mit Eis",
            "spec-3-desc": "Feiner gefüllter Crepe-Teig, serviert mit Vanille- und Schokoladeneis.",
            "reviews-subtitle": "Kundenservice",
            "reviews-title": "Was unsere Kunden sagen",
            "reviews-cta": "Alle Bewertungen ansehen",
            "loc-subtitle": "Finden Sie uns",
            "loc-title": "Standort & Kontakt",
            "loc-hours": "Täglich geöffnet: 12:00 - 00:00",
            "service-subtitle": "Exzellenz und Wärme",
            "service-title": "Unser Service",
            "service-p1": "Wir sind stolz darauf, einen außergewöhnlichen Kundenservice zu bieten. Unser Team ist bestrebt, jeden Besuch zu etwas Besonderem zu machen und einen aufmerksamen, professionellen und freundlichen Service zu bieten.",
            "service-p2": "Vom Moment an, in dem Sie durch unsere Tür treten, ist es unser Ziel, dass Sie sich wie zu Hause fühlen, eine einladende Atmosphäre genießen und eine personalisierte Aufmerksamkeit erhalten, die bis ins kleinste Detail geht.",
            // Dishes
            "dish-alcachofa": "Konfitierte Artischocke",
            "dish-tortilla": "Spanische Tortilla",
            "dish-morcilla": "Blutwurst aus Burgos mit Paprika",
            "dish-queso-cabra": "Ziegenkäse auf Öltost",
            "dish-chistorra": "Chistorra-Wurst",
            "dish-ensaladilla": "Russischer Salat",
            "dish-tequenos": "Tequeños (Käsestangen)",
            "dish-albondigas": "Kalbsfleischbällchen mit Pommes",
            "dish-torrezno": "Schweinekruste aus Soria mit Guacamole",
            "dish-cerdo-salsa": "Schweinefleisch in Sauce",
            "dish-bravas": "Patatas Bravas (scharfe Kartoffeln)",
            "dish-tortillita-camarones": "Garnelenpuffer",
            "dish-brocheta-gambas": "Garnelenspieß",
            "dish-mini-hamburguesa": "Spezial-Mini-Burger",
            "dish-bao-carrillada": "Bao-Brötchen mit Schweinebäckchen",
            "dish-tartar-atun": "Thunfisch-Tartar-Taco mit Wakame",
            "dish-patatas-fritas": "Pommes Frites",
            "tosta-payoyo": "Payoyo-Käse, Tomate und geräucherte Sardine",
            "tosta-manchego": "Manchego-Creme mit ibirischem Schinken",
            "tosta-bacalao": "Geräucherter Kabeljau mit frischer Tomate",
            "tosta-sardina": "Geräucherte Sardine mit frischer Tomate",
            "tosta-camembert": "Camembert-Creme mit ibirischem Schinken",
            "tosta-brie": "Brie-Käse mit karamellisierten Zwiebeln",
            "tosta-iberico": "Ibirischer Schinken",
            "tosta-salmon": "Frischkäse mit geräuchertem Lachs",
            "tosta-mechada": "Zupffleisch mit frischer Tomate",
            "starter-boquerones": "Sardellen in Essig",
            "starter-carpaccio": "Steak-Carpaccio mit Parmesan",
            "starter-padron": "Padrón-Paprika",
            "starter-croquetas-rabo": "Ochsenschwanz-Kroketten",
            "starter-croquetas-jamon": "Ibirische Schinkenkroketten",
            "starter-croquetas-variadas": "Gemischte Kroketten (8 Stk.)",
            "starter-croquetas-variadas-desc": "Schinken, Ochsenschwanz, Spanferkel mit Apfel und Kürbis mit Parmesan",
            "starter-anchoas": "Kantabrische Sardellen",
            "starter-quesos": "Gemischte Käseplatte",
            "starter-huevos-rotos": "Spiegeleier mit ibirischem Schinken",
            "starter-jamon": "Ibirischer Schinken",
            "starter-lomo": "Ibirische Lendenwurst (Caña de Lomo)",
            "starter-surtido": "Komplette ibirische Auswahl",
            "starter-chorizo": "Ibirische Chorizo",
            "starter-salchichon": "Ibirische Salchichón",
            "starter-manchego": "Reiner Manchego-Käse",
            "starter-payoyo": "Payoyo-Käse",
            "starter-camembert": "Frittierter Camembert-Käse",
            "salad-gazpacho": "Andalusisches Gazpacho",
            "salad-salmorejo": "Salmorejo aus Córdoba",
            "salad-queso-cabra": "Ziegenkäsesalat",
            "salad-tomate-simple": "Marinierte Tomate",
            "salad-tomate": "Marinierte Tomate mit Thunfischbauch",
            "salad-burratina": "Burratina-Salat",
            "salad-patio": "El Patio Antiguo Salat",
            "fish-mejillones": "Miesmuscheln nach Bearnaise-Art",
            "fish-salmon": "Gegrillter Lachs",
            "fish-pulpo": "Krake nach galicischer Art",
            "fish-pulpo-parrilla": "Halbe gegrillte Krake mit Kartoffelbrei",
            "fish-pez-espada": "Gegrillter Schwertfisch",
            "fish-pilpil": "Garnelen Pil Pil",
            "fish-almejas": "Knoblauchmuscheln",
            "fish-calamar": "Nationaler gegrillter Tintenfisch",
            "meat-rabo-toro": "Ochsenschwanz-Mille-feuille",
            "meat-cordero": "Milchlammkoteletts",
            "meat-entrecot": "Rinder-Entrecote (350 g)",
            "meat-chuleton": "Rinder-Chuletón (850 g)",
            "meat-secreto": "Secreto Ibérico (Eichelmast)",
            "meat-carrillada": "Schweinebäckchen in Syrah-Sauce",
            "meat-costilla-ternera": "Gebratene Kalbsrippe",
            "meat-costilla-cerdo": "BBQ-Schweinerippchen",
            "dessert-coulant": "Schokoladen-Coulant",
            "dessert-brownie": "Brownie mit Vanilleeis",
            "dessert-manzana": "Apfeltartelette mit Eis",
            "dessert-helado": "Vanille-Schokoladeneis",
            "dessert-crepes": "Crepes mit Nutella und Eis",
            "dessert-tarta-queso": "Pistazien-Käsekuchen"
        }
    };

    const langLinks = document.querySelectorAll('.lang-link');
    const currentLangSpan = document.getElementById('current-lang');

    function changeLanguage(lang) {
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            if (translations[lang] && translations[lang][key]) {
                el.textContent = translations[lang][key];
            }
        });
        if (currentLangSpan) currentLangSpan.textContent = lang.toUpperCase();
        localStorage.setItem('preferredLang', lang);
    }

    if (langLinks) {
        langLinks.forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                const lang = link.getAttribute('data-lang');
                changeLanguage(lang);
            });
        });
    }

    const savedLang = localStorage.getItem('preferredLang') || 'es';
    if (savedLang !== 'es') changeLanguage(savedLang);

    // 7. Menu Tabs Logic
    const menuTabs = document.querySelectorAll('.menu-tab');
    const menuSections = document.querySelectorAll('.menu-section');

    if (menuTabs.length > 0) {
        menuTabs.forEach(tab => {
            tab.addEventListener('click', () => {
                const target = tab.getAttribute('data-target');

                // Update tabs
                menuTabs.forEach(t => t.classList.remove('active'));
                tab.classList.add('active');

                // Update sections
                menuSections.forEach(section => {
                    if (section.id === target) {
                        section.classList.add('active');
                        // Trigger reveal for the newly shown section
                        const sectionReveals = section.querySelectorAll('.reveal');
                        sectionReveals.forEach(el => el.classList.add('active'));
                    } else {
                        section.classList.remove('active');
                    }
                });
            });
        });
    }
});
